Python 安装
-------------------

在使用 Python 进行开发前，先安装上 Python吧。

.. toctree::
   :maxdepth: 2

   install.rst

代码编写工具
-----------------------

选择一个合适的工具开始编写 Python 代码吧。

.. toctree::
   :maxdepth: 2

   coding_tools.rst

开发环境管理
-----------------------

开启多线程模式，试着在多个 Python 开发环境中无缝切换吧。

.. toctree::
   :maxdepth: 2

   environment.rst

Python 框架
-----------------------

避免重复造轮子，选择一个好用的框架吧。

.. toctree::
   :maxdepth: 2

   frameworks.rst

Python 文档资料
-----------------------

吃饭，睡觉，阅读文档吧。

.. toctree::
   :maxdepth: 2

   documents.rst
